### PR TITLE
adds the friend page UI

### PR DESCRIPTION
**Pull request by JamesClark123**
I had a weird issue come up where I was only able to apply webkit scroll styles in a separate css file. If anyone knows how to do this with Material UI I would appreciate advice on a solution

### CODE REVIEW

**Comment by aeciorc** [comment]
> I had a weird issue come up where I was only able to apply webkit scroll styles in a separate css file. If anyone knows how to do this with Material UI I would appreciate advice on a solution

Did you try this?
` '&::-webkit-scrollbar' : {....} `

**Comment by aeciorc** [comment]
It looks good though, one thing I noticed is that the contents of "following" and "suggested" are inverted. Also add a search bar to find users on either tabs. Maybe instead of the "suggested" tab it could be "discover", and when the search query is empty it gives you a list of suggestions. It's not on the mock, so you are free to be creative with it and implement it the way you want

**Comment by JamesClark123** [comment]
> > I had a weird issue come up where I was only able to apply webkit scroll styles in a separate css file. If anyone knows how to do this with Material UI I would appreciate advice on a solution
> 
> Did you try this?
> `'&::-webkit-scrollbar' : {....}`

Lol I swear that's the first thing I tried but I guess I had a typo - very frustrating

**Comment by JamesClark123** [comment]
`

> It looks good though, one thing I noticed is that the contents of "following" and "suggested" are inverted. Also add a search bar to find users on either tabs. Maybe instead of the "suggested" tab it could be "discover", and when the search query is empty it gives you a list of suggestions. It's not on the mock, so you are free to be creative with it and implement it the way you want

done with implementing this, gonna merge now. I tried to keep the search bar as simple as possible and as close to the original design. I think the suggested vs discover tab is a good idea & will be easy to implement when this gets hooked up with the backend

**Pull request merged**
